version: '3.8'

services:
  config-service:
    image: config-service
    build: config
    restart: always
    healthcheck:
      test: curl http://localhost:8888 || exit 1
      interval: 5s
      timeout: 3s
    networks:
      - news_ntwrk
    ports:
      - "8888:8888"

  senla-course:
    build:
      dockerfile: Dockerfile
      context: ./
    image: senla-course
    depends_on:
      db-tasks:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - news_ntwrk
    ports:
      - "8080:8080"

  db-tasks:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 3s
    networks:
      - news_ntwrk

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitorining/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - news_ntwrk

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitorining/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - news_ntwrk

networks:
  news_ntwrk:
