###1.CREATE USER_PROFILE
POST http://localhost:8080/senla/api/v0/user_profiles
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Иванов",
  "position": 1,
  "department": 2,
  "user": 1
}

<> 2024-09-27T195606.201.json
<> 2024-09-27T171653.201.json

###2.GET_ALL USER_PROFILE
GET http://localhost:8080/senla/api/v0/user_profiles

<> 2024-09-27T195610.200.json
<> 2024-09-27T171837.200.json

###3.GET_BY_ID USER_PROFILE
GET http://localhost:8080/senla/api/v0/user_profiles/1

<> 2024-09-27T195612.200.json
<> 2024-09-27T172040.200.json
<> 2024-09-27T171939.200.json

###4.UPDATE USER_PROFILE
PUT http://localhost:8080/senla/api/v0/user_profiles/1
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Сидоров",
  "position": 1,
  "department": 2,
  "user": 1
}

<> 2024-09-27T195614.200.json
<> 2024-09-27T172213.200.json

###5.DELETE USER_PROFILE
DELETE http://localhost:8080/senla/api/v0/user_profiles
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Сидоров",
  "position": 1,
  "department": 2,
  "user": 1
}



### 1.CREATE COMMENT
POST  http://localhost:8080/senla/api/v0/comments
Content-Type: application/json

{
  "task": 1,
  "usersProfile": 2,
  "commentText": "Это пример комментария для проверки.",
  "createdAt": "2024-09-27T12:34:56"
}

### 2.GET ALL COMMENT
GET  http://localhost:8080/senla/api/v0/comments

### 3.GET BY ID COMMENT
GET  http://localhost:8080/senla/api/v0/comments/1


### 3.UPDATE COMMENT
PUT http://localhost:8080/senla/api/v0/comments/1
Content-Type: application/json

{
  "task": 1,
  "usersProfile": 2,
  "commentText": "Это пример комментария для проверки.",
  "createdAt": "2024-09-27T12:34:56"
}


### 4.DELETE COMMENT
DELETE http://localhost:8080/senla/api/v0/comments
Content-Type: application/json

{
  "task": 1,
  "usersProfile": 2,
  "commentText": "Это пример комментария для проверки.",
  "createdAt": "2024-09-27T12:34:56"
}



####################################################################
### 1.CREATE DEPARTMENT?
POST  http://localhost:8080/senla/api/v0/departments
Content-Type: application/json

{
  "name": "SALES"
}

<> 2024-10-01T175421.201.json
<> 2024-10-01T174049.500.html
<> 2024-10-01T173311.500.html
<> 2024-10-01T172520.500.html
<> 2024-10-01T103451.500.html
<> 2024-10-01T103315.500.html
<> 2024-10-01T102822.500.html
<> 2024-09-28T113555.500.json
<> 2024-09-28T113327.500.json
<> 2024-09-28T113236.500.json
<> 2024-09-28T113030.500.json
<> 2024-09-28T112859.500.json
<> 2024-09-28T112627.500.json
<> 2024-09-28T112420.500.json
<> 2024-09-28T112251.500.json
<> 2024-09-28T112209.500.json
<> 2024-09-28T112105.500.json
<> 2024-09-28T111950.500.json
<> 2024-09-28T111754.500.json
<> 2024-09-28T111520.500.json
<> 2024-09-28T111411.404.json
<> 2024-09-28T111311.404.json
<> 2024-09-28T111259.404.json
<> 2024-09-28T111122.404.json
<> 2024-09-28T111057.404.json
<> 2024-09-28T100730.500.html
<> 2024-09-27T205848.500.html
<> 2024-09-27T173827.500.html

###2.GET_BY_ID DEPARTMENT
GET http://localhost:8080/api/v0/departments

<> 2024-09-28T113306.200.json
<> 2024-09-28T111435.404.json
<> 2024-09-28T111156.404.json
<> 2024-09-28T111149.404.json
<> 2024-09-27T173706.200.json

###3.GET_ALL DEPARTMENT
GET  http://localhost:8080/senla/api/v0/departments

<> 2024-10-01T174124.200.json
<> 2024-10-01T173240.200.json
<> 2024-09-28T111441.404.json
<> 2024-09-28T111431.404.json
<> 2024-09-27T174002.200.json

###4.UPDATE DEPARTMENT
PUT http://localhost:8080/senla/api/v0/departments/4
Content-Type: application/json

{
  "name": "SALES"
}

<> 2024-10-01T175428.200.json
<> 2024-10-01T175300.500.html

####################################################################



### 1.CREATE PROJECT
POST  http://localhost:8080/senla/api/v0/projects
Content-Type: application/json

{
    "name": "New Project",
    "projectCode": "NP-001",
    "description": "This is a new project.",
    "startDate": "2024-09-27T10:00:00",
    "endDate": "2024-12-27T10:00:00",
    "owner": 1
}

<> 2024-09-27T202020.201.json
<> 2024-09-27T174137.500.html

### 2.GET ALL PROJECT
GET  http://localhost:8080/senla/api/v0/projects

<> 2024-09-27T205532.200.json
<> 2024-09-27T174340.200.json

### 3.GET BY ID PROJECT
GET  http://localhost:8080/senla/api/v0/projects/1

<> 2024-09-27T174415.200.json

### 4.UPDATE PROJECT
PUT http://localhost:8080/senla/api/v0/projects/1
Content-Type: application/json

{
  "name": "Update Project",
  "projectCode": "NP-001",
  "description": "This is a new project.",
  "startDate": "2024-09-27T10:00:00",
  "endDate": "2024-12-27T10:00:00",
  "owner": 1
}

<> 2024-09-27T202159.200.json
### 5.DELETE PROJECT
DELETE http://localhost:8080/senla/api/v0/projects
Content-Type: application/json

{
  "name": "Delete Project",
  "projectCode": "NP-001",
  "description": "This is a new project.",
  "startDate": "2024-09-27T10:00:00",
  "endDate": "2024-12-27T10:00:00",
  "owner": 1
}




###1.CREATE TASK
POST  http://localhost:8080/senla/api/v0/tasks
Content-Type: application/json

{
  "name": "Task 1",
  "assignedTo": 1,
  "createdBy": 2,
  "project": 3,
  "dueDate": "2024-10-01T12:00:00",
  "status": "COMPLETED",
  "priority": "MEDIUM"
}

<> 2024-10-01T174033.201.json
<> 2024-09-28T104000.400.html
<> 2024-09-28T103914.500.html
<> 2024-09-28T103213.500.html
<> 2024-09-28T102423.500.html
<> 2024-09-28T101637.500.html
<> 2024-09-28T100755.500.html
<> 2024-09-27T174739.500.html
### 2.GET ALL TASK
GET  http://localhost:8080/senla/api/v0/tasks

<> 2024-09-27T203918.200.json
<> 2024-09-27T203809.404.html
<> 2024-09-27T202501.200.json
### 3.GET BY ID TASK
GET  http://localhost:8080/senla/api/v0/tasks/1

<> 2024-09-27T202533.200.json
### 4.UPDATE TASK
PUT http://localhost:8080/senla/api/v0/tasks/1
Content-Type: application/json

{
  "name": "Update проект",
  "assignedTo": 1,
  "createdBy": 2,
  "project": 3,
  "dueDate": "2024-09-30T12:00:00",
  "status": "IN_PROGRESS",
  "priority": "MEDIUM"
}

<> 2024-10-01T174001.200.json

### 4.DELETE TASK
DELETE http://localhost:8080/senla/api/v0/tasks
Content-Type: application/json

{
  "name": "Завершить проект",
  "assignedTo": 1,
  "createdBy": 2,
  "project": 3,
  "dueDate": "2024-09-30T12:00:00",
  "status": "IN_PROGRESS",
  "priority": "HIGH"
}

### ADMIN TOKEN
POST http://localhost:8080/senla/api/v0/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "securepassword123",
  "role": 1
}

### USER TOKEN
POST http://localhost:8080/senla/api/v0/auth/register
Content-Type: application/json

{
  "email": "guest@example.com",
  "password": "securepassword123",
  "role": 2
}

### GUEST TOKEN
POST http://localhost:8080/senla/api/v0/auth/register
Content-Type: application/json

{
  "email": "guest@example.com",
  "password": "guestpassword789",
  "role": 3
}



