spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  security:
    secret: 2A462D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778
    issuer: Senla
  mail:
    username: testsenderemailexample@gmail.com
    password: vhpp euxu sppa uevm
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  cron: "0 0 9 * * ?"

management:
  endpoints:
    web:
      exposure:
        include: "*"
