package ru.senla.model.entity.enums;

public enum PositionType {
  MANAGER,
  DEVELOPER,
  SALESPERSON,
  MARKETING_SPECIALIST,
  HR,
  ANALYST,
  ENGINEER,
  DESIGNER,
  PRODUCT_OWNER,
  QA_ENGINEER,
  SUPPORT_SPECIALIST,
  FINANCIAL_OFFICER,
  CONSULTANT,
  RECRUITER,
  DATA_SCIENTIST
}
